env_name: HalfCheetah-v4
save_dir: ./tmp/
seed: 42
eval_episodes: 10
log_interval: 1000
eval_interval: 5000
batch_size: 256
max_steps: 1e6
policy_steps: 20
start_training: 1e4
model_update_interval: 1000
tqdm: True
wandb: True
save_video: False

algo_kwargs:
  actor_lr: 3e-4
  critic_lr: 3e-4
  temp_lr: 3e-4
  model_lr: 3e-4
  critic_hidden_dims: [512, 512]
  actor_hidden_dims: [256, 256]
  model_hidden_dims: [200, 200, 200, 200]
  discount: 0.99
  tau: 0.005
  target_entropy: 
  backup_entropy: True
  critic_reduction: min
  init_temperature: 1.0
  n_ensemble: 8
  n_elites: 5
  